// <auto-generated />
using System;
using ClinicaLiberated.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaLiberated.Migrations
{
    [DbContext(typeof(ClinicaContext))]
    partial class ClinicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClinicaLiberated.Models.AgendamentoModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cpfPaciente")
                        .HasColumnType("longtext");

                    b.Property<string>("crmMedico")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dataHoraAgendamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("especialidadeMedico")
                        .HasColumnType("longtext");

                    b.Property<bool>("medicoPresente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nomeMedico")
                        .HasColumnType("longtext");

                    b.Property<string>("nomePaciente")
                        .HasColumnType("longtext");

                    b.Property<bool>("pacientePresente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("telefonePaciente")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("ClinicaLiberated.Models.ChamadaModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SalaConsultorio")
                        .HasColumnType("longtext");

                    b.Property<string>("nomePaciente")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Chamadas");
                });

            modelBuilder.Entity("ClinicaLiberated.Models.MedicoModel", b =>
                {
                    b.Property<string>("crm")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("dataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("especialidade")
                        .HasColumnType("longtext");

                    b.Property<string>("nomeCompleto")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("crm");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("ClinicaLiberated.Models.PacienteModel", b =>
                {
                    b.Property<string>("cpf")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("dataNascimento")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("nomeCompleto")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("cpf");

                    b.ToTable("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
